apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce-app
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: e-commerce-app
  template:
    metadata:
      labels:
        app: e-commerce-app
    spec:
      containers:
      - name: e-commerce-app
        image: mohammadikram/multibranch-flask-app:build-1
        ports:
        - containerPort: 5000